cmake_minimum_required(VERSION 3.13)

add_executable(
  UTEST_XmlParser
  UTEST_XmlParser.cpp
  ${IADI_XML_PARSER_SRC}
)

target_include_directories(
  UTEST_XmlParser
  PRIVATE ${GENERAL_MOCKS_ROOT}/log
  PRIVATE ${CMAKE_SOURCE_DIR}
)

target_link_libraries(
  UTEST_XmlParser
  GTest::gtest_main GTest::gmock
)

include(GoogleTest)

gtest_add_tests(
  TARGET UTEST_XmlParser
  TEST_SUFFIX .noArgs
  TEST_LIST noArgsTests
)

set_tests_properties(${noArgsTests} PROPERTIES TIMEOUT 600)
